<?php
// Heading
$_['heading_title']              = 'OKU Validation';

// Text
$_['text_oku']                   = 'OKU ID (#%s)';
$_['text_success']               = 'Success: You have modified OKU Form!';
$_['text_list']                  = 'OKU Validation List';
$_['text_updated_list']          = 'Printed On: ';
$_['text_total_number_of_entry'] = 'Total Number Of Entry: ';
$_['text_save_success']          = 'Success: You have save the record as PDF File!';

// Column (done)
$_['column_no']                  = 'No.';
$_['column_oku_id']              = 'OKU ID';
$_['column_name']                = 'Name';
$_['column_passport_no']         = 'Passport No.';
$_['column_gender']              = 'Gender';
$_['column_nationality']         = 'Nationality';
$_['column_category_id']         = 'Category ID';
$_['column_category']            = 'Category';
$_['column_justification']       = 'Justification';
$_['column_loname']              = 'Lo. Name';
$_['column_date_added']          = 'Date Added';
$_['column_action']              = 'Action';

//Entry
$_['entry_oku_id']               = 'OKU ID';
$_['entry_name']                 = 'Name';
$_['entry_category']             = 'Category';
$_['entry_gender']               = 'Gender';
$_['entry_nationality']          = 'Nationality';
$_['entry_date_added']           = 'Date Added';
$_['entry_loname']               = 'LO Name';


// Help
$_['help_override']              = 'If the customers order is being blocked from changing the order status due to an anti-fraud extension enable override.';

// Error
$_['error_warning']              = 'Warning: Please check the form carefully for errors!';
$_['error_permission']           = 'Warning: You do not have permission to modify orders!';
$_['error_action']               = 'Warning: Could not complete this action!';
$_['error_filetype']             = 'Invalid file type!';

//Controller text
$_['text_male']                  = 'Male';
$_['text_female']                = 'Female';
$_['text_no_justification']      = 'No Justification';

//view(validation_form)
$_['text_fullName']              = 'Full Name     :';
$_['text_passportNo']            = 'Passport No   :';
$_['text_gender']                = 'Gender        :';
$_['text_nationality']           = 'Nationality   :';
$_['text_categoryOKU']           = 'Category OKU  :';
$_['text_justification']         = 'Justification :';
$_['text_photo']                 = 'Photo         :';
$_['text_LOName']                = 'LO Name       :';
$_['text_ticketGenerated']       = 'Ticket Generated By:' ;
$_['text_approved']              = 'Approved By:';

//button
$_['button_print_pdf']      = 'Print OKU List';
$_['button_print']          = ' View PDF';
$_['button_back']           = ' Back';